config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'
      }

  root to: 'pages#home'
  resources :cars do
    resources :bookings, only: [:create]
  end

  get "/bookings/:id/accept", to: 'bookings#accept', as: 'accept'
  get "/bookings/:id/decline", to: 'bookings#decline', as: 'decline'

  resources :users, only: [:show]

  get "/dashboard", to: 'users#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cars, dependent: :destroy
  has_many :bookings
  validates :first_name, presence: true
  validates :last_name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  mount_uploader :photo, PhotoUploader

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end
    return user
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:new, :create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
    #super
  #end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def dashboard
    if user_signed_in?
      @user = current_user
    else
      redirect_to root_path, notice: "Sign in to see your dashboard!"
    end
    @user = current_user
  end
end

app/views/users/dashboard.html.erb
<div class="container">
  <h1><%= "Hi #{@user.first_name}!" %></h1>
  <div class="main-container full-padded">
    <div id="profile" class="full-padded">

      <% if @user.photo.file.nil? && @user.facebook_picture_url.nil? %>
      <div class="empty-picture-small"">
        <p>-- No picture --</p>
      </div>
      <% else %>
      <div class="user-photo text-center">
        <% if @user.photo.file.nil? %>
          <%= image_tag @user.facebook_picture_url, height: 200, width: 150 %>
        <% else%>
          <%= cl_image_tag @user.photo, height: 200, width: 150, crop: :fill, :radius=>10 %>
        <% end%>
      </div>
      <% end %>
      <div id="info" class="full-padded">
        <!-- <ul> -->
          <p><%= "First name: #{@user.first_name}" %></p>
          <p><%= "Last name: #{@user.last_name}" %></p>
          <!-- </ul> -->
          <%= link_to "Change credentials...", "\#", class: "btn-sm" %>
        </div>
      </div>
      <div style="flex: 1 0 auto;">
        <div class="full-padded" style="display: flex; justify-content: space-between;align-items: center;">
          <!-- <div class="full-padded"> -->
            <h1 style="margin:0;">Cars</h1>
            <div >
              <%= link_to "Add new car", new_car_path, class: "btn btn-md" %>
            </div>
        </div>
        <div id="cars">
          <% if @user.cars.empty? %>
          No cars yet...
          <% else %>
          <% @user.cars.each do |car| %>
          <div class="car" style="display: flex; justify-content: space-around; padding: 15px; margin: 15px; position: relative; background-color: #e0e0e0;border-radius: 15px">
            <div style="width: 250px;text-align: center">
              <%= link_to car_path(car) do %>
                <h4 style="font-family: $body-font !important"><%= "#{car.make} #{car.model}" %></h4>
                <div class="thumb-wrapper">
                  <% if car.car_photos[car.cover_photo].nil? %>
                    <div class="empty-thumbnail">
                      <p>-- No picture --</p>
                    </div>
                  <% else %>
                    <div class="pic-thumbnail" style="background-image: url(<%= car.car_photos[car.cover_photo].photo.url(:thumbnail) %>);">
                    </div>
                  <% end %>
                </div>
              <% end %>
              <%= link_to "Edit car", "#", class: "btn-sm" %>
              <%= link_to "Remove car", car_path(car), class: "btn-sm btn-danger", method: :delete %>
            </div>
            <div class="simple-calendar ">
              <%= month_calendar(attribute: :start_date, end_attribute: :end_date, events: car.bookings) do |date, bookings| %>

                <%= date.day %>

                <% bookings.each do |booking| %>
                  <% case booking.status %>
                    <% when "pending" %>
                        <i class="fas fa-square" style="color: orange;"></i>
                    <% when "accepted" %>
                      <i class="fas fa-square" style="color: green;"></i>
                    <% when "declined" %>
                      <i class="fas fa-square" style="color: gray;"></i>
                    <% when "ongoing" %>
                      <i class="fas fa-square" style="color: blue;"></i>
                    <% when "completed" %>
                      <i class="fas fa-square" style="color: black;"></i>
                  <% end %>
                <% end %>
              <% end %>
            </div>
            <div style="text-align: center">
              <h3>Incoming booking</h3>
              <% if !car.next_booking.nil? %>
                <%= link_to user_path(car.next_booking.user) do %>
                <div style="text-align:center;">
                  <%= car.next_booking.user.first_name%> <%= car.next_booking.user.last_name%>
                  <div class="thumb-wrapper">
                    <% if car.next_booking.user.photo.file.nil? %>
                      <div class="empty-thumbnail-small">
                        <p>-- No picture --</p>
                      </div>
                    <% else %>
                      <div class="pic-thumbnail-small" style="background-image: url(<%= car.next_booking.user.photo.url(:thumbnail) %>);">
                      </div>
                    <% end %>
                  </div>
                </div>
                <% end %>

                  <div>
                    <p>
                      <%= car.next_booking.start_date.strftime("%d %B %Y") %> -
                                  <%= car.next_booking.end_date.strftime("%d %B %Y") %>
                    </p>
                    <% case car.next_booking.status %>
                      <% when "pending" %>
                        <div class="div-booking-status pending">
                        <div>
                          <%= car.next_booking.status.capitalize%></div>
                          <%= link_to "Accept", accept_path(car.next_booking), class: "btn-sm btn-success" %>
                          <%= link_to "Decline", decline_path(car.next_booking), class: "btn-sm btn-danger" %>
                        </div>
                      <% when "accepted" %>
                        <div class="div-booking-status accepted">
                        <div>
                          <%= car.next_booking.status.capitalize%></div>
                          <%= link_to "Cancel", decline_path(car.next_booking), class: "btn-sm btn-danger" %>
                        </div>
                      <% when "declined" %>
                        <div class="div-booking-status declined">
                        <div>
                          <%= car.next_booking.status.capitalize%></div>
                          <%= link_to "Accept", accept_path(car.next_booking), class: "btn-sm btn-success" %>
                        </div>
                      <% when "ongoing" %>
                        <div class="div-booking-status ongoing">
                        <div>
                          <%= car.next_booking.status.capitalize%></div>
                        </div>
                      <% when "completed" %>
                        <div class="div-booking-status completed">
                        <div>
                          <%= car.next_booking.status.capitalize%></div>
                        </div>
                    <% end %>

                  </div>

              <% else %>
                <p>No bookings for your <%= "#{car.make} #{car.model}"%> just yet.</p>
              <% end %>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<div class="container">
  <div>
    <% if @user.photo.file.nil? %>
      <div class="empty-picture"">
        <p>-- No picture --</p>
      </div>
    <% else %>
      <div class="user-photo text-center">
        <%= cl_image_tag @user.photo, height: 400, width: 300, crop: :fill, :radius=>10 %>
      </div>
    <% end %>
  </div>
</div>