config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'
      }

  root to: 'pages#home'
  resources :cars do
    resources :bookings, only: [:create]
  end

  get "/bookings/:id/accept", to: 'bookings#accept', as: 'accept'
  get "/bookings/:id/decline", to: 'bookings#decline', as: 'decline'

  resources :users, only: [:show]

  get "/dashboard", to: 'users#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <h2>The classic ride to make your dreams come true</h2>
    <!-- <a class="btn">Start Your Journey Here</a> -->
    <%= link_to "Start Your Journey Here", cars_path, class: "btn" %>
  </div>
</div>

app/views/layouts/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-questions">
    <h6>Classic Rides</h6>
    <p>About Us | FAQs | Terms of Service</p>
  </div>
  <div class="footer-links">
    <a href=""><i class="fab fa-instagram"></i></a>
    <a href=""><i class="fab fa-facebook-square"></i></a>
    <a href=""><i class="fab fa-twitter-square"></i></a>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div id="brand-text" class="header_h1">
    <h1><%= link_to "Classic Rides", root_path, class: "header_h1" %></h1>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">

    <%= link_to "Search", cars_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Journeys</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Messages</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <% if user_signed_in? %>
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Dashboard", dashboard_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      <% else %>
        <%= link_to "Signin", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link"%>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv='X-UA_compatible' content="IE=edge,chrome=1">

  <title>Classic Rides</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
  <link href="https://fonts.googleapis.com/css?family=Cabin:400,700|Lobster" rel="stylesheet">
</head>
<body>
  <%= render "layouts/navbar" %>
  <div class="page-content">
    <%= render "layouts/flashes" %>
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js" %>
  <%= javascript_pack_tag 'application' %>
  <%= javascript_pack_tag 'maps' %>
</body>
</html>